trigger:
  - '*'

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET SDK 6.x'
    inputs:
      packageType: sdk
      version: '6.x'

  - task: NodeTool@0
    displayName: 'Use Node.js 16.x'
    inputs:
      versionSpec: '16.x'

  - task: Npm@1
    displayName: 'Install npm dependencies'
    inputs:
      command: 'ci'  # lub 'install' jeśli nie używasz lockfile
      verbose: false

  # Jeśli używasz gulp lokalnie
  - script: 'npx gulp'
    displayName: 'Run gulp tasks'

  # Jeśli chcesz kompilować Sass, użyj Dart Sass zamiast node-sass
  - script: 'npx sass Tailspin.SpaceGame.Web/wwwroot:Tailspin.SpaceGame.Web/wwwroot'
    displayName: 'Compile Sass assets'

  - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
    displayName: 'Write build info'
    workingDirectory: Tailspin.SpaceGame.Web/wwwroot

  - task: DotNetCoreCLI@2
    displayName: 'Restore project dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build the project - Release'
    inputs:
      command: 'build'
      arguments: '--no-restore --configuration Release'
      projects: '**/*.csproj'